# Generated by Django 3.2.23 on 2023-12-12 18:15

from django.db import migrations, models
import nautobot.core.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0099_remove_dangling_note_objects'),
        ('poc_core_model_extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
