# Generated by Django 3.2.19 on 2023-10-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0009_alter_vlan_name'),
        ('poc_core_model_extension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='mymodel', to='ipam.IPAddress'),
        ),
    ]
