# Generated by Django 3.2.23 on 2023-12-13 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0038_vlan_group_name_unique_remove_slug'),
        ('poc_core_model_extension', '0002_auto_20231212_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModelToIPAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ipam.ipaddress')),
                ('mymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poc_core_model_extension.mymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mymodel',
            name='ip_addresses',
            field=models.ManyToManyField(blank=True, related_name='mymodel', through='poc_core_model_extension.MyModelToIPAddress', to='ipam.IPAddress'),
        ),
    ]
