# Generated by Django 4.2.17 on 2025-01-21 17:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0067_controllermanageddevicegroup_tenant'),
        ('poc_core_model_extension', '0003_auto_20231213_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModelToLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dcim.location')),
                ('mymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poc_core_model_extension.mymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mymodel',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='mymodel', through='poc_core_model_extension.MyModelToLocation', to='dcim.location'),
        ),
    ]
